# Generated by bios init bash. Do not paste this into your rc file.
# Put this one line at the end of ~/.bashrc instead, so it stays current:
#   command -v bios >/dev/null 2>&1 && eval "$(bios init bash)"
#
# Bash has no equivalent of zsh's `print -z`. READLINE_LINE only does
# anything from inside a `bind -x` key binding while readline is already
# reading a line, and this hook runs at shell startup, before readline's
# prompt loop has begun, so there is no way here to push keys typed during
# the boot show back onto the command line. They are read and discarded
# rather than faked back.
if [[ $- == *i* ]] && command -v bios >/dev/null 2>&1; then
  bios boot --hook >/dev/null
  export SPARKLEBIOS_BOOTED=1
  export SPARKLEBIOS_HOOK={{HOOK_HASH}}
  export SPARKLEBIOS_HOOK_SHELL={{HOOK_SHELL}}

  # `bios resume` prints a path. A command cannot change its caller's working
  # directory, so the function does the cd.
  bios() {
    if [[ "$1" == resume ]]; then
      local _sparklebios_dir
      _sparklebios_dir="$(command bios resume "${@:2}")" || return $?
      if [[ -n "$_sparklebios_dir" ]]; then
        builtin cd -- "$_sparklebios_dir"
      fi
    else
      command bios "$@"
    fi
  }
  if [[ {{PRESENCE}} == 1 ]]; then
    # The mascot, as a placement of an image already sent to the terminal. Empty where the
    # terminal cannot draw one. Put it at the front of your prompt, in double quotes, AFTER this
    # line and after anything else that sets PS1:
    #   PS1="$SPARKLEBIOS_MASCOT$PS1"
    # Double quotes on purpose: the placement never changes, so it is expanded once, here.
    #
    # The old placement is kept only long enough to compare against the new one: a second
    # `eval "$(bios init bash)"` in the same shell (same flavour, same terminal) would
    # otherwise resend an image the terminal already has, every time it is run.
    _sparklebios_prev_mascot="${SPARKLEBIOS_MASCOT-}"
    export SPARKLEBIOS_MASCOT={{MASCOT}}
    # The image itself is sent once, here. Every prompt after that costs only the placement.
    _sparklebios_image={{MASCOT_IMAGE}}
    if [ -n "$_sparklebios_image" ] && [ "$_sparklebios_prev_mascot" != "$SPARKLEBIOS_MASCOT" ]; then
      printf '%s' "$_sparklebios_image"
    fi
    unset _sparklebios_image _sparklebios_prev_mascot

    _sparklebios_took() {
      local s=$1
      if (( s < 60 )); then
        printf '%ss' "$s"
      elif (( s < 3600 )); then
        printf '%sm %ss' "$(( s / 60 ))" "$(( s % 60 ))"
      else
        printf '%sh %sm' "$(( s / 3600 ))" "$(( (s % 3600) / 60 ))"
      fi
    }

    # bash has no preexec, so the timer starts from the DEBUG trap and is armed once per
    # command rather than once per line of a compound one.
    _sparklebios_preexec() {
      [[ -n "${COMP_LINE:-}" ]] && return
      [[ "$BASH_COMMAND" == _sparklebios_precmd ]] && return
      [[ -z "${_sparklebios_started:-}" ]] && _sparklebios_started=$SECONDS
    }

    _sparklebios_precmd() {
      local status_was=$?
      if [[ -n "${_sparklebios_started:-}" ]]; then
        local elapsed=$(( SECONDS - _sparklebios_started ))
        unset _sparklebios_started
        # 130 is Ctrl-C. Somebody who stopped a command does not need it described.
        if (( elapsed >= {{AFTER}} )) && (( status_was != 130 )); then
          local took
          took="$(_sparklebios_took $elapsed)"
          # The line is an argument, never part of the format, so nothing a flavour writes
          # is read as a printf directive or as shell.
          if (( status_was == 0 )); then
            printf '\e[90m%s\e[0m\n' {{DONE}}
          else
            printf '\e[90m%s\e[0m\n' {{FAILED}}
          fi
        fi
      fi
      # PROMPT_COMMAND is one semicolon-joined string: returning the status this function
      # opened with, rather than falling off the end with whatever its last `if` happened to
      # return, keeps it intact for whatever runs next in the chain, whatever order that is.
      return "$status_was"
    }

    trap '_sparklebios_preexec' DEBUG
    # A second `eval "$(bios init bash)"` in the same shell must not run precmd (and so
    # print the finish line) twice per prompt.
    if [[ "${PROMPT_COMMAND:-}" != *_sparklebios_precmd* ]]; then
      PROMPT_COMMAND="_sparklebios_precmd${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
    fi
    trap {{GOODBYE_TRAP}} EXIT

    # Only when nothing else already answers for a missing command.
    if ! declare -F command_not_found_handle >/dev/null 2>&1; then
      command_not_found_handle() {
        printf '%s: %s\n' {{NOT_FOUND}} "$1" >&2
        return 127
      }
    fi
  fi

  # Set on its own, independent of presence: the tab title is its own config key. Chained
  # into PROMPT_COMMAND ahead of anything presence just added, the same way and for the
  # same reason: so it keeps running, and keeps running only once, printed before the
  # finish line, the way it always has.
  if [[ {{TITLE}} == 1 ]]; then
    _sparklebios_title() {
      # PROMPT_COMMAND is one semicolon-joined string, so this function's own exit status
      # becomes `$?` for whatever runs next in the chain: capturing the real one here and
      # returning it at the end, rather than falling off the end with the `if`'s own status,
      # is what keeps a failing command from being reported as a success further down.
      local status_was=$?
      if [[ "$TERM" != dumb && "$TERM" != linux ]]; then
        printf '\e]0;%s %s\a' {{TITLE_NAME}} "${PWD/#$HOME/~}"
      fi
      return "$status_was"
    }
    if [[ "${PROMPT_COMMAND:-}" != *_sparklebios_title* ]]; then
      PROMPT_COMMAND="_sparklebios_title${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
    fi
  fi
  eval {{ULTRA}}
fi
